package:
  name: numpy
  version: 1.10.2

source:
  fn: numpy-1.10.2.tar.gz
  url: https://pypi.python.org/packages/source/n/numpy/numpy-1.10.2.tar.gz
  md5: 816518282f1617636aaf26e7cd9b127b

requirements:
  build:
    - gcc
    - libgfortran
    - openblas
    - python

  run:
    - openblas
    - python

build:
  string: py{{py}}_0

test:
  requires:
    - nose
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: https://www.numpy.org
  summary: "NumPy: array processing for numbers, strings, records, and objects."
  license: BSD
