package:
  name: numpy
  version: 1.9.3

source:
  fn: numpy-1.9.3.tar.gz
  url: https://pypi.python.org/packages/source/n/numpy/numpy-1.9.3.tar.gz
  md5: 7c321721ffc62c25bc854b8addf42f20

requirements:
  build:
    - python
    - libgfortran
    - openblas

  run:
    - python
    - libgfortran
    - openblas

build:
  string: py{{py}}_0

test:
  requires:
    - nose
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: https://www.numpy.org
  summary: "NumPy: array processing for numbers, strings, records, and objects."
  license: BSD
