package:
  name: sympy
  version: "0.7.6.1"

source:
  fn: sympy-0.7.6.1.tar.gz
  url: https://pypi.python.org/packages/source/s/sympy/sympy-0.7.6.1.tar.gz
  md5: 92e5b8e2f51c41ecac47b3458da1f505

requirements:
  build:
    - python
  run:
    - python

build:
  string: py{{ py }}_0

test:
  # Python imports
  imports:
    - sympy
    - sympy.assumptions
    - sympy.assumptions.handlers
    - sympy.benchmarks
    - sympy.calculus
    - sympy.categories
    - sympy.combinatorics
    - sympy.concrete
    - sympy.core
    - sympy.core.benchmarks
    - sympy.crypto
    - sympy.diffgeom
    - sympy.external
    - sympy.functions
    - sympy.functions.combinatorial
    - sympy.functions.elementary
    - sympy.functions.elementary.benchmarks
    - sympy.functions.special
    - sympy.functions.special.benchmarks
    - sympy.galgebra
    - sympy.geometry
    - sympy.integrals
    - sympy.integrals.benchmarks
    - sympy.interactive
    - sympy.liealgebras
    - sympy.logic
    - sympy.logic.algorithms
    - sympy.logic.benchmarks
    - sympy.logic.utilities
    - sympy.matrices
    - sympy.matrices.benchmarks
    - sympy.matrices.expressions
    - sympy.mpmath
    - sympy.mpmath.calculus
    - sympy.mpmath.functions
    - sympy.mpmath.libmp
    - sympy.mpmath.matrices
    - sympy.ntheory
    - sympy.parsing
    - sympy.physics
    - sympy.physics.hep
    - sympy.physics.mechanics
    - sympy.physics.optics
    - sympy.physics.quantum
    - sympy.physics.unitsystems
    - sympy.physics.unitsystems.systems
    - sympy.physics.vector
    - sympy.plotting
    - sympy.plotting.intervalmath
    - sympy.plotting.pygletplot
    - sympy.polys
    - sympy.polys.agca
    - sympy.polys.benchmarks
    - sympy.polys.domains
    - sympy.printing
    - sympy.printing.pretty
    - sympy.series
    - sympy.series.benchmarks
    - sympy.sets
    - sympy.simplify
    - sympy.solvers
    - sympy.solvers.benchmarks
    - sympy.stats
    - sympy.strategies
    - sympy.strategies.branch
    - sympy.tensor
    - sympy.unify
    - sympy.utilities
    - sympy.utilities.mathml
    - sympy.vector

about:
  home: http://www.sympy.org
  license: BSD License
  summary: 'Computer algebra system (CAS) in Python'
