package:
  name: sympy
  version: "0.7.4.1"

source:
  fn: sympy-0.7.4.1.tar.gz
  url: https://pypi.python.org/packages/source/s/sympy/sympy-0.7.4.1.tar.gz
  md5: 2547375b3b7eee17a3f1f4f3038c383d
  patches:
    - mpmath.patch

requirements:
  build:
    - python
  run:
    - python

build:
  string: py{{ py }}_0

test:
  # Python imports
  imports:
    - sympy
    - sympy.assumptions
    - sympy.assumptions.handlers
    - sympy.assumptions.tests
    - sympy.categories
    - sympy.categories.tests
    - sympy.combinatorics
    - sympy.combinatorics.tests
    - sympy.concrete
    - sympy.concrete.tests
    - sympy.core
    - sympy.core.tests
    - sympy.crypto
    - sympy.crypto.tests
    - sympy.diffgeom
    - sympy.diffgeom.tests
    - sympy.external
    - sympy.external.tests
    - sympy.functions
    - sympy.functions.combinatorial
    - sympy.functions.combinatorial.tests
    - sympy.functions.elementary
    - sympy.functions.elementary.tests
    - sympy.functions.special
    - sympy.functions.special.tests
    - sympy.galgebra
    - sympy.galgebra.tests
    - sympy.geometry
    - sympy.geometry.tests
    - sympy.integrals
    - sympy.integrals.tests
    - sympy.interactive
    - sympy.interactive.tests
    - sympy.liealgebras
    - sympy.liealgebras.tests
    - sympy.logic
    - sympy.logic.algorithms
    - sympy.logic.tests
    - sympy.logic.utilities
    - sympy.matrices
    - sympy.matrices.expressions
    - sympy.matrices.expressions.tests
    - sympy.matrices.tests
    - sympy.mpmath
    - sympy.mpmath.calculus
    - sympy.mpmath.functions
    - sympy.mpmath.libmp
    - sympy.mpmath.matrices
    - sympy.mpmath.tests
    - sympy.ntheory
    - sympy.ntheory.tests
    - sympy.parsing
    - sympy.parsing.tests
    - sympy.physics
    - sympy.physics.hep
    - sympy.physics.hep.tests
    - sympy.physics.mechanics
    - sympy.physics.mechanics.tests
    - sympy.physics.quantum
    - sympy.physics.quantum.tests
    - sympy.physics.tests
    - sympy.plotting
    - sympy.plotting.intervalmath
    - sympy.plotting.intervalmath.tests
    - sympy.plotting.pygletplot
    - sympy.plotting.pygletplot.tests
    - sympy.plotting.tests
    - sympy.polys
    - sympy.polys.agca
    - sympy.polys.agca.tests
    - sympy.polys.domains
    - sympy.polys.domains.tests
    - sympy.polys.tests
    - sympy.printing
    - sympy.printing.pretty
    - sympy.printing.pretty.tests
    - sympy.printing.tests
    - sympy.series
    - sympy.series.tests
    - sympy.sets
    - sympy.sets.tests
    - sympy.simplify
    - sympy.simplify.tests
    - sympy.solvers
    - sympy.solvers.tests
    - sympy.statistics
    - sympy.statistics.tests
    - sympy.stats
    - sympy.stats.tests
    - sympy.strategies
    - sympy.strategies.branch
    - sympy.strategies.branch.tests
    - sympy.strategies.tests
    - sympy.tensor
    - sympy.tensor.tests
    - sympy.unify
    - sympy.unify.tests
    - sympy.utilities
    - sympy.utilities.mathml
    - sympy.utilities.tests

about:
  home: http://www.sympy.org
  license: BSD License
  summary: 'Computer algebra system (CAS) in Python'
