package:
  name: numpy
  version: 1.8.1

source:
  fn: numpy-1.8.1.tar.gz
  url: https://pypi.python.org/packages/source/n/numpy/numpy-1.8.1.tar.gz
  md5: be95babe263bfa3428363d6db5b64678

requirements:
  build:
    - python
    - libgfortran
    - openblas

  run:
    - python
    - libgfortran
    - openblas

build:
  string: py{{py}}_0

test:
  requires:
    - nose
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: https://www.numpy.org
  license: BSD
