package:
  name: pydy
  version: "0.3.0"

source:
  fn: pydy-0.3.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pydy/pydy-0.3.0.tar.gz
  md5: 4f4812a4e989519149298e475561a7e9

requirements:
  build:
    - python
    - setuptools >=8.0
    - sympy >=0.7.4.1 # [py2k]
    - sympy >=0.7.5 # [py3k]
    - numpy >=1.7 # [py2k]
    - numpy >=1.9 # [py3k]
    - scipy >=0.11 # [py2k]
    - scipy >=0.14 # [py3k]
  run:
    - python
    - setuptools >=8.0
    - sympy >=0.7.4.1 # [py2k]
    - sympy >=0.7.5 # [py3k]
    - numpy >=1.7 # [py2k]
    - numpy >=1.9 # [py3k]
    - scipy >=0.11 # [py2k]
    - scipy >=0.14 # [py3k]

build:
  number: 0
  string: py{{py}}_0

test:
  requires:
    - nose
  imports:
    - pydy
    - pydy.codegen
    - pydy.codegen.tests
    - pydy.models
    - pydy.system
    - pydy.utils
    - pydy.viz
    - pydy.viz.tests

about:
  home: http://pydy.org
  license: The BSD 3-Clause License
  summary: 'Python tool kit for multi-body dynamics.'
