package:
  name: theano
  version: 0.7.0

source:
  fn: Theano-0.7.0.tar.gz
  url: https://pypi.python.org/packages/source/T/Theano/Theano-0.7.0.tar.gz
  md5: 099a9575801b71252b5bbbc3c34ed45a

build:
  number: 0
  string: np{{ np }}py{{ py }}_0

requirements:
  build:
    - gcc
    - python
    - setuptools
    - numpy x.x
    - scipy >=0.11
  run:
    - gcc
    - python
    - numpy x.x
    - scipy >=0.11

test:
  imports:
    - theano
    - theano.compile
    - theano.compile.sandbox
    - theano.compile.tests
    - theano.compat
    - theano.gof
    - theano.gof.tests
    - theano.misc
    - theano.misc.tests
    - theano.sandbox
    - theano.sandbox.cuda
    - theano.sandbox.cuda.tests
    - theano.sandbox.gpuarray
    - theano.sandbox.gpuarray.tests
    - theano.sandbox.linalg
    - theano.sandbox.linalg.tests
    - theano.sandbox.scan_module
    - theano.sandbox.scan_module.tests
    - theano.scalar
    - theano.scalar.tests
    - theano.scan_module
    - theano.scan_module.tests
    - theano.sparse
    - theano.sparse.sandbox
    - theano.sparse.tests
    - theano.tensor
    - theano.tensor.deprecated
    - theano.tensor.nnet
    - theano.tensor.nnet.tests
    - theano.tensor.signal
    - theano.tensor.signal.tests
    - theano.tensor.tests
    - theano.tests

about:
  home: http://deeplearning.net/software/theano/
  license: BSD License
  summary: 'Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.'
